authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')
]

basketapp/urls.py
from django.urls import path

from .views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from geekshop.views import index, contacts

urlpatterns = [
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contacts/', contacts, name='contacts'),
    path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='products_index'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>/', product, name='product'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,

    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категории'
        verbose_name_plural = 'категории'

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    is_active = models.BooleanField(default=True)


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория'
    )
    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )
    image = models.ImageField(
        upload_to='products_images',
        blank=True,
    )
    short_desc = models.CharField(
        verbose_name='краткое описание продукта',
        max_length=60,
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание продукта',
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='цена продукта',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0,
    )

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name} ({self.category.name}) - {self.pk}"

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

mainapp/views.py
from django.shortcuts import render
import random

from mainapp.models import Product, ProductCategory
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from django.conf import settings
from django.core.cache import cache


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter()
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter()


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True).order_by('price')


def get_same_products(hot_product):
    same_products = Product.objects.filter(is_active=True).select_related('category').exclude(pk=hot_product.pk)[:3]
    return same_products


def get_hot_product():
    products = get_products()
    return random.sample(list(products), 1)[0]


def products(request, pk=None, page=1):
    title = 'продукты'

    links_menu = get_links_menu()

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)[:4]
    products = get_products_orederd_by_price()

    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = products
            category = {'pk': 0, 'name': 'все'}
        else:
            category = get_category(pk)
            products = get_products_in_category_orederd_by_price(pk)

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'hot_product': hot_product,
            'related_products': same_products,
            'products': products_paginator,

        }
        return render(request, 'mainapp/products.html', context)

    products = Product.objects.all().order_by('price')

    context = {
        'title': title,
        'links_menu': links_menu,
        'hot_product': hot_product,
        'related_products': same_products,
        'products': products,

    }
    return render(request, 'mainapp/products.html', context)


def product(request, pk):
    title = 'продукты'
    links_menu = get_links_menu()

    product = get_product(pk)

    same_products = get_same_products(product)[:4]
    context = {
        'title': title,
        'links_menu': links_menu,
        'related_products': same_products,

        'product': product,

    }
    return render(request, 'mainapp/product.html', context)

mainapp/templates/mainapp/product.html
{% extends 'geekshop/base.html' %}

{% load static %}

{% block title %}Продукты{% endblock %}

{% block content_1 %}
<div class="hero-white">
    {% endblock %}

    {% block content %}
</div>

<div class="details">

    {% include 'mainapp/includes/inc_category_menu.html' %}

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ product.image }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="{% url 'basket:add' product.pk %}">
                        <img src="/media/{{ product.image }}" style="width: 100%" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="{% url 'basket:add' product.pk %}">
                        <img src="/media/{{ product.image }}" style="width: 100%" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="{% url 'basket:add' product.pk %}">
                        <img src="/media/{{ product.image }}" style="width: 100%" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ product.name }}</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price">{{ product.price }}<span>руб</span></p>
            <a href="{% url 'basket:add' product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                {{ product.description }}
            </div>
        </div>
    </div>

    <div class="related">
        <div class="title clearfix">
            <h2>Похожие продукты</h2>
            <a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
        </div>
        <div class="related-products clearfix" style="flex-wrap: nowrap">
            {% for product in related_products %}
            <div class="block">
                <a href="{% url 'basket:add' product.pk %}">
                    <img src="/media/{{ product.image }}" style="width: 100%" alt="{{ product.short_desc }}">
                    <div class="text">
                        <img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.short_desc }}</p>
                        <p>{{ product.category.name }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'geekshop/base.html' %}

{% load static %}

{% block title %}{{ title|title }}{% endblock %}

{% block content_1 %}
<div class="hero-white">
    {% endblock %}

    {% block content %}
</div>

<div class="details">

    {% include 'mainapp/includes/inc_category_menu.html' %}

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ hot_product.image }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" style="width: 100%" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" style="width: 100%" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" style="width: 100%" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ hot_product.name }}</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price">{{ hot_product.price }}<span>руб</span></p>
            <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                {{ hot_product.description }}
            </div>
        </div>
    </div>

    <div class="products_list">
        {% if category %}
        <div class="title clearfix">
            <h2>
                Категория: "{{ category.name|title }}"
            </h2>
        </div>
        {% endif %}

        <div class="paginator">
            {% if products.has_previous %}
            <a href="{% url 'products:page' category.pk products.previous_page_number %}">
                <
            </a>
            {% endif %}
            <span class="current">
            страница {{ products.number }} из
            {{ products.paginator.num_pages }}
          </span>
            {% if products.has_next %}
            <a href="{% url 'products:page' category.pk products.next_page_number %}">
                >
            </a>
            {% endif %}
        </div>

        <div class="related-products clearfix">
            {% for product in products %}
            <div class="block">
                <a href="{% url 'products:product' product.pk %}">
                    <img src="/media/{{ product.image }}" style="width: 100%" alt="product">
                    <div class="text">
                        <img src="{% static 'geekshop/img/icon-hover.png' %}" alt="hover">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.short_desc }} </p>
                        <p>{{ product.category.name }} </p>
                    </div>
                </a>
            </div>
            {% endfor %}

        </div>
    </div>

    <div class="related">
        <div class="title clearfix">
            <h2>Похожие продукты</h2>
            <a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
        </div>
        <div class="related-products clearfix" style="flex-wrap: nowrap">
            {% for product in related_products %}
            <div class="block">
                <a href="#"><img src="/media/{{ product.image }}" style="width: 100%" alt="{{ product.short_desc }}">
                    <div class="text">
                        <img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
                        <h4>{{ product.name }}</h4>
                        <p>{{ product.short_desc }}</p>
                        <p>{{ product.category.name }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}