adminapp/urls.py
from adminapp.views import (
    UsersListView,
    UsersCreateView,
    user_update,
    user_delete,
    category_create,
    categories,
    ProductCategoryUpdateView,
    category_delete,
    product_create,
    ProductDetailView,
    product_update,
    product_delete,
    products
    )
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', UsersCreateView.as_view(), name='user_create'),
    path('users/read/', UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', user_update, name='user_update'),
    path('users/delete/<int:pk>/', user_delete, name='user_delete'),

    path('categories/create/', category_create, name='category_create'),
    path('categories/read/', categories, name='categories'),
    path('categories/update/<int:pk>/', ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', product_create, name='product_create'),
    path('products/read/category/<int:pk>/', products, name='products'),
    path('products/read/<int:pk>/', ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', product_update, name='product_update'),
    path('products/delete/<int:pk>/', product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')
]

basketapp/urls.py
from django.urls import path

from .views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from geekshop.views import index, contacts

urlpatterns = [
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contacts/', contacts, name='contacts'),
    path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from .views import products, product

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='products_index'),
    path('category/<int:pk>/', products, name='category'),
    path('category/<int:pk>/page/<int:page>/', products, name='page'),
    path('product/<int:pk>/', product, name='product'),
]

ordersapp/urls.py
from django.urls import path

from ordersapp.views import OrderList,\
    order_forming_complete, \
    OrderItemsCreate, \
    OrderRead, \
    OrderUpdate, \
    OrderDelete, \
    get_product_price

app_name = 'ordersapp'

urlpatterns = [
    path('', OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/', order_forming_complete, name='order_forming_complete'),
    path('create/', OrderItemsCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='order_delete'),
    path('product/<int:pk>/price/', get_product_price, name='get_price'),
]

geekshop/views.py
from django.shortcuts import render


def index(request):
    title = 'магазин'
    context = {
        'title': title,

        'slogan': 'супер предложения',
    }
    return render(request, 'geekshop/index.html', context)


def contacts(request):
    title = 'контакты'
    context = {
        'title': title,

    }
    return render(request, 'geekshop/contact.html', context)

geekshop/templates/geekshop/includes/inc_footer.html
<div class="clr"></div>

<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB 2017</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
</div>

geekshop/templates/geekshop/includes/inc_main_menu.html
<div class="header clearfix">
    <a href="{% url 'index' %}" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'index' %}" class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">домой</a>
        </li>
        <li><a href="{% url 'products:products_index' %}"
               class="{% if request.resolver_match.namespace == 'products' %}active{% endif %}">продукты</a></li>
        <li><a href="{% url 'contacts' %}"
               class="{% if request.resolver_match.url_name == 'contacts' %}active{% endif %}">контакты</a></li>
        {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                    {{ user.first_name|default:'Пользователь' }}

                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'auth:edit' %}">
                            профиль
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'ordersapp:orders_list' %}">
                            заказы
                        </a>
                    </li>
                    {% if user.is_superuser %}
                    <li>
                        <a href="{% url 'admin_staff:users' %}">
                            админка
                        </a>
                    </li>
                    {% endif %}

                </ul>
                <a href="{% url 'basket:view' %} "
                   class="{% if request.resolver_match.namespace == 'basket' %}active{% endif %}">
                <span>
                    {% if basket %}
                        {{ basket.0.total_cost|floatformat:0 }} руб
                        ({{ basket.0.total_quantity }} шт)
                    {% endif %}
                </span>
                </a>
            </div>
        </li>


        {% endif %}
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">выйти</a>
            {% else %}
            <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>
    </ul>
    <a href="#" class="search"></a>
    <a href="#" class="basket"></a>
</div>