authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from geekshop.views import index, contacts

urlpatterns = [
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contacts/', contacts, name='contacts'),
    path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path

from ordersapp.views import OrderList,\
    order_forming_complete, \
    OrderItemsCreate, \
    OrderRead, \
    OrderUpdate, \
    OrderDelete, \
    get_product_price

app_name = 'ordersapp'

urlpatterns = [
    path('', OrderList.as_view(), name='orders_list'),
    path('forming/complete/<int:pk>/', order_forming_complete, name='order_forming_complete'),
    path('create/', OrderItemsCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', OrderRead.as_view(), name='order_read'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='order_update'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='order_delete'),
    path('product/<int:pk>/price/', get_product_price, name='get_price'),
]

ordersapp/models.py
from django.db import models

from django.conf import settings
from mainapp.models import Product


class OrderItemQuerySet(models.QuerySet):
    def delete(self, *args, **kwargs):
        for object in self:
            object.product.quantity += object.quantity
            object.product.save()
        super(OrderItemQuerySet, self).delete(*args, **kwargs)


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'отправлен в работу'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабтывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(verbose_name='статус',
                              max_length=3,
                              choices=ORDER_STATUS_CHOICES,
                              default=FORMING)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()

    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'total_cost': sum(list(map(lambda x: x.quantity * x.product.price, items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, items))),
        }


class OrderItem(models.Model):
    objects = OrderItemQuerySet.as_manager()

    order = models.ForeignKey(Order,
                              related_name='orderitems',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                verbose_name='продукт',
                                on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество',
                                           default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    def delete(self):
        self.product.quantity += self.quantity
        self.product.save()

        super(self.__class__, self).delete()

ordersapp/forms.py
from django import forms

from mainapp.models import Product
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            self.fields['product'].queryset = Product.get_items()
            field.widget.attrs['class'] = 'form-control'

ordersapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.forms import inlineformset_factory

from basketapp.models import Basket
from ordersapp.forms import OrderItemForm
from ordersapp.models import Order, OrderItem
from mainapp.models import Product


class OrderList(LoginRequiredMixin, ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemsCreate(LoginRequiredMixin, CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('order:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
                    # basket_items[num].delete()
                basket_items.delete()
            else:
                formset = OrderFormSet()

        data['orderitems'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderItemsCreate, self).form_valid(form)


class OrderUpdate(LoginRequiredMixin, UpdateView):
    model = Order
    fields = []
    # context_object_name = 'object'
    success_url = reverse_lazy('order:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price

            data['orderitems'] = formset

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        # удаляем пустой заказ
        if self.object.get_total_cost() == 0:
            self.object.delete()

        return super(OrderUpdate, self).form_valid(form)


class OrderDelete(LoginRequiredMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('order:orders_list')


class OrderRead(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'ordersapp/order_detail.html'

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['title'] = 'заказ/просмотр'
        return context


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('order:orders_list'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if update_fields == 'quantity' or 'product':
        if instance.pk:
            instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
        else:
            instance.product.quantity -= instance.quantity
        instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()


def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.filter(pk=int(pk)).first()
        if product:
            return JsonResponse({'price': product.price})
        else:
            return JsonResponse({'price': 0})

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block js %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'ordersapp/js/script.js' %}"></script>
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="container">
            <div class="row">
                <div class="p-4">
                   <div class="category_delete">
                       <div class="h1">Уверены, что хотите удалить?</div>
                       {% include 'ordersapp/includes/inc_order_summary.html' %}
                       <form action="{% url 'order:order_delete' object.pk %}" method="post">
                           {% csrf_token %}
                           <input class="btn btn-danger" type="submit" value="удалить">
                       </form>
                       <button class="btn btn-success mt-4">
                           <a href="{% url 'order:orders_list' %}">отмена</a>
                       </button>
                   </div>
                </div>

            </div>
        </div>
    {% endif %}
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "geekshop/base.html" %}
{% load static %}

{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="basket_list">
       {% for item in object.orderitems.select_related %}
           <div class="basket_record">
               <img src="{{ item.product.image }}"
                    alt="{{ item.product.short_desc }}">
               <span class="category_name">
                   {{ item.product.category.name }}
               </span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
               <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
               <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
           </div>
       {% endfor %}
   </div>
   {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "geekshop/base.html" %}
{% load static %}

{% load cache %}


{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="order_form">
       <form action="" method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <table class="table">
               {{ orderitems.management_form }}
               {% for form in orderitems.forms %}
                   {% if forloop.first %}
                       <thead>
                       <tr>
                           {% for field in form.visible_fields %}
                               <th class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                                   {{ field.label|capfirst }}
                               </th>
                           {% endfor %}
                       </tr>
                       </thead>
                   {% endif %}
                   <tr class="formset_row">
                       {% for field in form.visible_fields %}
                           <td class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                               {% if forloop.first %}
                                   {% for hidden in form.hidden_fields %}
                                       {{ hidden }}
                                   {% endfor %}
                               {% endif %}
                               {{ field.errors.as_ul }}
                               {% if field.name != 'price' %}
                                        {% cache 3600 orderitemform_product field.value %}}
                                            {{ field }}
                                        {% endcache %}
                               {% else %}
                                    {% if field.value %}
                                        <span class="orderitems-{{forloop.parentloop.counter0}}-price">
                                            {{ field.value }}
                                        </span> руб
                                    {% endif %}
                               {% endif %}
                           </td>
                       {% endfor %}
                   </tr>
               {% endfor %}
           </table>
           <button type="submit" value="сохранить"
                   class="btn btn-success btn-round form-control last">
               сохранить
           </button>
           {% include 'ordersapp/includes/inc_order_actions.html' %}
       </form>
   </div>

{% block js %}
    <script src="{% static '/ordersapp/script.js' %}"></script>
    <script src="{% static '/ordersapp/jquery.formset.js' %}"></script>
{% endblock %}

{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'geekshop/base.html' %}
{% load static %}


{% block content %}
   <div class="h2 text-center head">
       Ваши заказы,
       {% if user.first_name %}
           {{ user.first_name|title}}
       {% else %}
           Пользователь
       {% endif %}
   </div>
   <table class="table orders_list">
       <thead>
         <tr>
           <th>ID</th>
           <th>Создан</th>
           <th>Обновлен</th>
           <th>Статус</th>
         </tr>
       </thead>
       <tbody>
           {% for item in object_list %}
               {% if item.is_active %}
               <tr>
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'order:order_read' item.pk %}">
                           посмотреть
                       </a>
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'order:order_update' item.pk %}">
                           редактировать
                         </a>
                       {% endif %}
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'order:order_delete' item.pk %}">
                             удалить
                         </a>
                       {% endif %}
                   </td>
               </tr>
               {% endif %}
           {% endfor %}
       </tbody>
   </table>
   <button class="btn btn-default btn-round">
       <a href="{% url 'index' %}">
           на главную
       </a>
   </button>
   <button class="btn btn-default btn-round">
       <a href="{% url 'order:order_create' %}">
           новый
       </a>
   </button>
{% endblock %}